CREATE TABLE [dbo].[EMPLOYEES]
(
	[ID] INT NOT NULL PRIMARY KEY,
	[NAME] CHAR(64) NOT NULL,
	[COMPANY_ID] INT NOT NULL,
	[EXPERIENCE] INT NOT NULL, 
    [STARTING_DATE] DATETIME NOT NULL, 
    [SALARY] FLOAT NOT NULL, 
    [VACATION_DAYS] INT NOT NULL, 
    CONSTRAINT [FK_EMPLOYEES_ToCOMPANIES] FOREIGN KEY ([COMPANY_ID]) REFERENCES [COMPANIES]([ID]),
)
GO
